services:
  - type: web
    name: iglu-backend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
